type: user-collection
displayName: User License Plates
get:
    responses:
        200:
            body:
                application/json:
                    example: |
                        [
                            {
                                "licensePlateId": 12354,
                                "licensePlateNr": "ZH727222",
                                "vignetteNrs": [
                                    "23492302349"
                                ],
                                "changeablePlate": false,
                                "licensePlateTypeId": 1,
                                "licensePlateCountryId": 3
                            }
                        ]
                    schema: |
                        [
                            {
                                licensePlateId: 'integer',
                                licensePlateNr: 'string',
                                vignetteNrs: ['string'],
                                changeablePlate: 'boolean',
                                licensePlateTypeId: 'integer',
                                licensePlateCountryId: 'integer'
                            }
                        ]

post:
    body:
        application/json:
            example: |
                {
                    "licensePlateNr": "ZH727222",
                    "vignetteNrs": [
                        "23492302349"
                    ],
                    "changeablePlate": false,
                    "licensePlateTypeId": 1,
                    "licensePlateCountryId": 3
                }
            schema: |
                licensePlateNr: 'string'
                vignetteNrs: ['string']
                changeablePlate: 'boolean'
                licensePlateTypeId: 'integer'
                licensePlateCountryId: 'integer'


/{licensePlateId}:
    type: user-collection-item
    put:
        body:
            application/json:
                example: |
                    {
                        "licensePlateNr": "ZH727222",
                        "vignetteNrs": [
                            "23492302349"
                        ],
                        "changeablePlate": false,
                        "licensePlateTypeId": 1,
                        "licensePlateCountryId": 3
                    }
                schema: |
                    licensePlateNr: 'string'
                    vignetteNrs: ['string']
                    changeablePlate: 'boolean'
                    licensePlateTypeId: 'integer'
                    licensePlateCountryId: 'integer'
    delete:
