/account: !include ./account.raml
/logins: !include ./logins.raml
/balance:
    is: [secured]
    securedBy: [sessionToken]
    description: money balance

/reminders:
    is: [secured]
    securedBy: [sessionToken]
    description: Manage reminders

/badges:
    type: user-collection
    displayName: User Badges
    get:
        description: Get a list of all badges
    post:
        description: Order/Register new badge

    /{badgeId}:
        type: user-collection-item
        displayName: One User Badge


/license-plates: !include license-plate.raml


/badge-permits:
    type: user-collection
    displayName: Badge Permits
    post:
    get:
    /{badgePermitId}:
        type: user-collection-item

/license-plate-permits:
    type: user-collection
    displayName: License Plate Permits
    post:
    get:
    /{licensePlatePermitId}:
        type: user-collection-item

/badge-transactions:
    type: user-collection
    post:
    get:

/license-plate-transactions:
    type: user-collection
    post:
    get:
    /{licensePlateTransactionId}:
        type: user-collection-item
        patch:
            description: stop a license plate transaction
