#%RAML 0.8
baseUri: http://server/api/{version}
title: Vendaro ParkingCard Api
version: 1
protocols: [ HTTPS ]
mediaType: application/json
documentation:
    - title: About this Specification
      content: !include about-this-spec.md
    - title: General Information
      content: !include general-information.md

securitySchemes:
    - sessionToken:
        type: x-sessionToken
        description: "A session token is needed"
        describedBy:
            headers:
                Cookie:
                    type: string

    - basicAuth:
        type: Basic Authentication
        description: user / password authentication
        describedBy:
            headers:
                Authorization:
                    type: string

traits:
    - secured:
        headers:
            Cookie:
                example: 68a5sdf67jvbza3jie3
                required: true
                type: string
        responses:
            401:
                description: Session id not valid or expired

            403:
                description: Valid user is not authorized
    - error-body-returning:
        responses:
            400:
                description: Request has failed
                body:
                    application/json:
                        schema: !include error.cson

resourceTypes:

  - user-collection:
        is: [secured]
        securedBy: [sessionToken]
        get:
            displayName: Get the list of <<resourcePathName>> of a user
        post:
            is: [error-body-returning]
            displayName: Create a new user <<resourcePathName|!singularize>>

  - user-collection-item:
        is: [secured, error-body-returning]
        securedBy: [sessionToken]
        put:
            displayName: Update <<resourcePathName|!singularize>> of a user
            responses:
                204:
                    description: Successfully updated <<resourcePathName|!singularize>>
                404:
                    description: <<resourcePathName|!singularize>> not found

        delete:
            displayName: Delete <<resourcePathName|!singularize>> of a user
            responses:
                204:
                    description: Successfully deleted <<resourcePathName|!singularize>>
                404:
                    description: <<resourcePathName|!singularize>> not found


schemas:
    - MultiLangString: |
        # a translated string
        de: 'string'
        fr: 'string'
        it: 'string'

      Error: |
        # a generic error
        code: 'integer'
        message:
            de: 'string'
            fr: 'string'
            it: 'string'

      FieldError: |
        # an error regarding a certain field
        code: 'integer'
        fieldName: 'string'
        message:
            de: 'string'
            fr: 'string'
            it: 'string'

      Address: |
        #an address that allows for either a company or a private person
        salutationLine: 'string'
        company1: 'string'
        company2: 'string'
        firstName: 'string'
        lastName: 'string'
        street1: 'string'
        street2: 'string'
        zipCode: 'string'
        city: 'string'
        countryId: 'integer'

        $required: 'street1 zipCode city countryId'


/user: !include ./user/user.raml

/badge-locations:
    get:
        description: get a list of all the possible badge locations
    /{locationId}:
        /permits:
            get:
                description: get all possible permits for a location

/license-plate-locations:
    get:
        description: get a list of all the possible license plate locations
    /{locationId}:
        /permits:
            get:
                description: get all possible permits for a location

/public-license-plate-permit:
    post:
        description: order a license plate permit without an user-account

/meta: !include ./meta/meta.raml

