#%RAML 0.8
baseUri: http://server/api/{version}
title: Vendaro ParkingCard Api
version: 1
protocols: [ HTTPS ]
mediaType: application/json
documentation:
    - title: About this Specification
      content: !include about-this-spec.md
    - title: General Information
      content: !include general-information.md

securitySchemes:
    - sessionToken:
        type: x-sessionToken
        description: "A session token is needed"
        describedBy:
            headers:
                Cookie:
                    type: string

    - basicAuth:
        type: Basic Authentication
        description: user / password authentication
        describedBy:
            headers:
                Authorization:
                    type: string

traits:
    - secured:
        headers:
            Cookie:
                description: JSESSIONID
                required: true
                type: string
        responses:
            401:
                description: Session id not valid or expired

schemas:
    - customTypes: !include ./customTypes.cson


/user: !include ./user/user.raml

/badge-locations:
    get:
        description: get a list of all the possible badge locations
    /{locationId}:
        /permits:
            get:
                description: get all possible permits for a location

/license-plate-locations:
    get:
        description: get a list of all the possible license plate locations
    /{locationId}:
        /permits:
            get:
                description: get all possible permits for a location

/public-license-plate-permit:
    post:
        description: order a license plate permit without an user-account

/meta: !include ./meta/meta.raml

